### ISSUE TITLE
list expansions?

### ISSUE THREAD

**Issue by junqdu** [gameshelf/gameshelf.github.io#11]
with the option for user to check whether to display or not in the help page
 

- [x] display expansions
- [x] add data for expansion
- [x] more filter for expansion

**Comment by janscarton** [comment]
This is important because it will often change the number of supported players. For example Scythe supports 1-5 players, but the Invaders from Afar expansion extends the max player count to 7.

**Comment by janscarton** [comment]
I've been looking through my collection with this in mind. The vast majority of expansions are NOT appropriate to include in the app. They would just needlessly pollute the results. It would be nice to be able to flag those expansions you wish to include at BGG. Perhaps "Want to Play" would be an appropriate option?

**Comment by junqdu** [comment]
@janscarton Maybe I can add some customizable options to display exps that pass the criteria, e.g. average rating 7+, and/with "Want to Play" status.
Since "Want to Play" unlike "Owned", it could have different definition for different users. For me I only flag unplayed game "Want to Play", once it is played, I won't use that flag anymore, even though I do want to play.

**Comment by janscarton** [comment]
User-configurable expansion inclusion criteria sounds like a great option. I certainly can't think of a better way to handle this problem!

**Comment by junqdu** [comment]
@janscarton 
I start to wonder if I should move all the expansions to a new tab, since they will be in the end of the list and they got no rank.
![screen shot 2018-01-04 at 10 46 07 pm](https://user-images.githubusercontent.com/4250728/34598357-18f08c7a-f1a1-11e7-9c50-f58e36d27703.png)
