### ISSUE TITLE
"Shelf" view of all games / Grid view

### ISSUE THREAD

**Issue by Rvervuurt** [gameshelf/gameshelf.github.io#12]
I wrote some custom CSS to display all games in a "shelf" view.
<img width="1531" alt="screen shot 2018-01-05 at 14 27 58" src="https://user-images.githubusercontent.com/1439765/34611185-c340dfc6-f224-11e7-985f-883675719591.png">

I tried to create a pull-request, but I have no idea how (I barely use Github...), so I just paste the CSS below. All that's needed from your side, is a button that toggles the class `shelf_view` on `table`, the CSS should do the rest!

Filtering still works, btw! It's also responsive, because of   ##flexbox.

```
table {
	transition: all .4s ease-in;
}

table.shelf_view tr th {
	display: none;
	transition: all .4s ease-in;
}


table.shelf_view tbody {
	display: flex;
	flex-wrap: wrap;
	justify-content: space-around;
	transition: all .4s ease-in;
}

table.shelf_view tr {
	background-color: transparent !important;
	float: left;
	flex-basis: 20%;
	text-align: center;
	margin-bottom: 20px;
	transition: all .4s ease-in;
}

table.shelf_view tr td {
	border: none !important;
	text-align: center;
	width: 100%;
	display: block;
	position: relative;
	transition: all .4s ease-in;
}

table.shelf_view tr td img {
	height: 150px;
	width: auto;
	transition: all .4s ease-in;
}

table.shelf_view tr td a {
	display: block;
	transition: all .4s ease-in;
}

table.shelf_view tr td:not(:first-child) {
	display: none;
	transition: all .4s ease-in;
}

**Comment by junqdu** [comment]
@Rvervuurt check it out
