### ISSUE TITLE
I have 415 "Owned" games recorded on BGG but only 240 show up

### ISSUE THREAD

**Issue by millca** [gameshelf/gameshelf.github.io#14]
I read your help section but that still doesn't help solve the bug I've run into.

As you can see by looking at my BGG profile, I OWNED 415 games (not expansions) but only 240 are showing up. https://boardgamegeek.com/user/clmdvd

Thanks for helping me out. I really like what you are doing here! Fantastic tool!

**Comment by junqdu** [comment]
boardgame = standalone + expansion
<img width="385" alt="screen shot 2018-01-05 at 10 57 49 am" src="https://user-images.githubusercontent.com/4250728/34623718-55b47764-f207-11e7-9dd6-6fec7b216308.png">
415-174=241, and you probably have a duplicate in your collection, which becomes 240.

You could also exclude expansions.
<img width="522" alt="screen shot 2018-01-05 at 10 59 10 am" src="https://user-images.githubusercontent.com/4250728/34623771-7b5e89d2-f207-11e7-9fda-c4cee91742e6.png">
