### ISSUE TITLE
r.stats.rating.ranks.rank is undefined

### ISSUE THREAD

**Issue by ericfrancis** [gameshelf/gameshelf.github.io#31]
Steps to reproduce:

1. https://gameshelf.github.io/help
1. enter userid
1. Click collection

Message: `r.stats.rating.ranks.rank is undefined`

**Comment by junqdu** [comment]
@ericfrancis which user id did you use?

**Comment by ericfrancis** [comment]
dadoprso

**Comment by junqdu** [comment]
@ericfrancis fixed

**Comment by ericfrancis** [comment]
Working now, thanks!
