### ISSUE TITLE
notification location for "Get Me A Game"

### ISSUE THREAD

**Issue by r36huang** [gameshelf/gameshelf.github.io#33]
the randomly selected game popup blocks the button for a random game, so if the first two randomized results aren't what you're looking for, you have to wait for the notifications to disappear before you can randomize again

**Comment by junqdu** [comment]
it can be swiped away

**Comment by r36huang** [comment]
is there a way to do this on a pc?

**Comment by junqdu** [comment]
@r36huang hold the popup and drag it left or right

**Comment by r36huang** [comment]
would it be possible to make it go away by clicking? if i'm on a touchpad click and hold is a bit complicated and unintuitive

**Comment by r36huang** [comment]
if it's too much trouble then dont worry about it
