### ISSUE TITLE
Internet Explorer ;)

### ISSUE THREAD

**Issue by florianAT** [gameshelf/gameshelf.github.io#39]
Thanks for a very usefool tool! 

I accidentally used InternetExplorer 11 today - the page would not load with the error message: 
<Object doesn't support property or method 'includes'>. Is this a problem of the javascript-libraries you used or in your code somewhere?

**Comment by junqdu** [comment]
@florianAT sorry, not going to fix problem in IE, you could user your the browser on your phone to view the site.
