### ISSUE TITLE
Collection not loading

### ISSUE THREAD

**Issue by fromeea** [gameshelf/gameshelf.github.io#45]
When I try to view my collection the working wheel never stops spinning after BGG finishes processing.  I have used your site in the past without issue but in the last couple months this issue has occurred. It does display my "Latest 100 Plays" without issue.  
My username on BGG is fromeea.

**Comment by junqdu** [comment]
>Owned | 2770

@fromeea interesting, was you collection always that big?

**Comment by fromeea** [comment]
Yes. It has been in the 2500+ range for a long time. I have not done any big jumps recently. Just slow growth.

If you need a video or screenshots let me know.

Thanks,
Eric

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by junqdu** [comment]
@fromeea 
I did a bit of investigation on the issue, it appeared that your data just exceed the limit of localStorage of the browser, which is 10MB. It seems like it is fixable by using another type of storage instead of localStorage, IndexedDB.

I been quite busy with work and life, but I might be able to implement the fix maybe this weekend or the next.

**Comment by fromeea** [comment]
Thank you for investigating this issue.
Please let me know when you have implemented the fix.

Eric.
________________________________

**Comment by junqdu** [comment]
@fromeea it should be fixed now, if you got to the Help page and check the "Disable Local Storage", you should be able to load your collection again.

In case you are wondering, I experimented with IndexedDB, but failed to implemented for our usage, so I went with disabling the caching feature.

**Comment by fromeea** [comment]
It works great!
It is really nice to have it back!
________________________________
