### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by lackovic** [gameshelf/gameshelf.github.io#50]
It looks like the site is not working anymore, I used to visit the following address to get the list of owned games:

https://gameshelf.github.io/?userId=Proteldon&ownedgames=true

but now it shows an empty list. Has something changed?

**Comment by HolisticDeveloper** [comment]
@lackovic have you tried clicking the Clear Cache button on the [help page](https://gameshelf.github.io/help/)? That worked for me.

**Comment by lackovic** [comment]
It's working now.
